services:
  couchdb:
    restart: always
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: doom
    image: couchdb:latest
    ports:
      - "666:5984"
  angular_front:
    build:
        context: ./front
    ports:
      - '4200:4200'
  backend:
    build:
        context: ./server
    ports:
      - '3000:3000'
    
