services:
  couchd:
    restart: always
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: doom
    image: couchdb:latest
    ports:
      - "666:5984"
  angular_front:
    build:
        context: ./front
    ports:
      - '4200:4200'
